# Generated by Django 5.1.2 on 2024-10-23 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatos',
            name='data',
            field=models.DateField(default=datetime.date(2024, 10, 23)),
        ),
        migrations.AddField(
            model_name='vagas',
            name='data',
            field=models.DateField(default=datetime.date(2024, 10, 23)),
        ),
    ]
