# Generated by Django 5.1.2 on 2024-10-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_candidatos_data_vagas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatos',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='data',
            field=models.DateField(),
        ),
    ]
