# Generated by Django 5.1.2 on 2024-10-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0003_alter_candidatos_data_alter_vagas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
