# Generated by Django 5.1.2 on 2024-10-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0004_alter_vagas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatos',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
